### ISSUE TITLE
Incorrect Order of Two-Column Features - Mobile

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#7]
**Description:**

When users visit the Event Details page from (www.qa-test.julie-chan.ca/EventDetails.php), the two-column features are displaying an incorrect order on smaller screens. Instead of the intended sequence of an image followed by the context, the current layout shows a mismatched arrangement of text and images.

**Steps to Reproduce:**

This bug is found on all mobile devices and browsers:

1.	Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)/EventDetails.php
2.	Click Event Details from navigation menu
3.	Scroll down after the event schedule section to event features in the following order:
a.	Network Bingo: text, image, 
b.	Headshot Photobooth: image, text,
c.	Digital Mural: text, image, image, text.
d.	Snack and Refreshments: Image, text

**Expected Result:**

We expect when users visit the Event Details page, after scrolling down to the two-column features, the following pattern is used

-	Image: Image of the event feature
-	Title: 2–3 words title on the event feature
-	Description: A short paragraph on the event feature

**Actual Result:**

Refer to the attached documents for screenshot of bug.

**iPhone - Safari**
![bug6-event-details](https://github.com/SeleneChoi/QA/assets/115045111/525b3d10-26eb-44f4-87c6-e18db11c214a)

**Comment by Jpduque25** [comment]
Had to implement responsive design using tailwindCSS utility class to create a consistent image->text column. When users change screen size, the original image, disappears with the use of utility class

hidden lg: block

When users are viewing it through mobile, there is another duplicate image however it is only viewed on mobile and not on desktop due to the class lg : hidden  

By inserting two duplicate images with different screen responsiveness, i was able to create a consistent layout that is applied throughout this page.
